// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Azone.Merchant.Migrations
{
    [DbContext(typeof(MerchantDbContext))]
    [Migration("20260111162308_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Azone.Merchant.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("ShopOwner", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopId1")
                        .HasColumnType("integer");

                    b.HasKey("ShopId", "UserId");

                    b.HasIndex("ShopId1");

                    b.ToTable("ShopOwners");
                });

            modelBuilder.Entity("ShopOwner", b =>
                {
                    b.HasOne("Azone.Merchant.Models.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Azone.Merchant.Models.Shop", null)
                        .WithMany("Owners")
                        .HasForeignKey("ShopId1");
                });

            modelBuilder.Entity("Azone.Merchant.Models.Shop", b =>
                {
                    b.Navigation("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
