syntax = "proto3";

option csharp_namespace = "Azone.Contracts.Models.Generated";

import "common/common_types.proto";


package auth;


service Auth {
  rpc CreateAccount(CreateAccountRequest) returns (CreateAccountReply);
  rpc Login(LoginRequest) returns (LoginReply);
  rpc Logout(RefreshToken) returns (common.IsSuccess);
  rpc Refresh(RefreshToken) returns (TokenPair);
  rpc ChangePassword(ChangePasswordRequest) returns (common.IsSuccess);
  rpc GetUserData(common.UserId) returns (UserData);
  rpc UserExist(common.UserId) returns (common.IsSuccess);
}

message CreateAccountRequest {
  string password = 1;
  string login = 2;
}

message ChangePasswordRequest {
  string login = 1;
  string password = 2;
  string new_password = 3;
}

message UserData {
  int32 id = 1;
  
}

message RefreshToken {
  string refresh = 1;
}

message CreateAccountReply {
  TokenPair tokens = 1;
}

message LoginRequest {
  string password = 1;
  string login = 2;
}

message LoginReply {
  TokenPair tokens = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}


message TokenPair {
  string refresh_token = 1;
  string access_token = 2;
}
