<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Azone.Infra.Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Protobuf Include="Protos\auth.proto" Services="Both" Access="Public"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.28.2" />
      <PackageReference Include="Grpc.Core.Api" Version="2.64.0" />
      <PackageReference Include="Grpc.Tools" Version="2.76.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
